### ISSUE TITLE
To-dos

### ISSUE THREAD

**Issue by perploug** [zalando-incubator/transformer#1]
- [x] [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) updated
- [x] [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md) updated with names of external contributors
- [x] [CODEOWNERS](../blob/master/.github/CODEOWNERS) updated with usernames of who review which PRs
- [x] [MAINTAINERS](../blob/master/MAINTAINERS) updated with team member contact info
- [x] [CODE_OF_CONDUCT.md](../blob/master/CODE_OF_CONDUCT.md) reviewed
- [x] [SECURITY.md](../blob/master/SECURITY.md) reviewed
- [x] [Pull request template](../blob/master/.github/PULL_REQUEST_TEMPLATE.md) reviewed
- [x] [Issue template](../blob/master/.github/ISSUE_TEMPLATE.md) reviewed
- [x] [Readme](../blob/master/README.md) updated

**Comment by thilp** [comment]
Also:
- [ ] Update the README of https://github.bus.zalan.do/TIP/transformer, announcing that all development has moved here.
- [x] Archive https://github.bus.zalan.do/TIP/transformer.
- [ ] Fix the link to CONTRIBUTORS.md in the sentence "See also the list of contributors who participated in this project" of the README.
- [ ] Manually import all tests from https://github.bus.zalan.do/TIP/transformer — the automatic open-sourcing tool missed them.
- [ ] Fix the links to the authors' GitHub profiles in the README.
- [ ] Update the project's URL in `setup.py`.

This comes from the internal issue TIP/docs#417.

**Comment by tortila** [comment]
FYI I just renamed the repository to `transformer` (lowercase). The URL with capitalized T continues to work: https://github.com/zalando-incubator/Transformer. Given that it was the only outstanding action item, I'm closing this issue
