### ISSUE TITLE
In the documentation, links to compare releases are broken

### ISSUE THREAD

**Issue by tortila** [zalando-incubator/Transformer#50]
https://transformer.readthedocs.io/en/latest/Changelog.html contains "Diff" link for each release to compare the changes between current and previous release. The links look like this one: https://github.com/zalando-incubator/transformer/compare/v1.1.2...v1.1.3 and redirect to GitHub. Because we don't track the releases (or any other meaningful tags) in GitHub, these links show a message "There isn’t anything to compare".

**Transformer version**
1.1.3 and older

**To Reproduce**
1. Open https://transformer.readthedocs.io/en/latest/Changelog.html
2. Click on any of the "Diff" links

**Expected behaviour**
Either make the links valid (e.g. [by publishing a release to GitHub](https://developer.github.com/v3/repos/releases/#create-a-release) at the same time we publish it to PyPI) or get rid of the broken links altogether.

**Screenshots**
<img width="877" alt="Screen Shot 2019-04-29 at 17 10 55" src="https://user-images.githubusercontent.com/5598055/56906074-d22db300-6aa1-11e9-8c18-49eadc820a24.png">

**Comment by thilp** [comment]
Good catch! I don't remember well what is implied by releases but I think only pushing git tags with the corresponding names is enough to make the links work as intended — I remember doing it shortly after we open-sourcing Transformer.

**Comment by tortila** [comment]
I manually created and pushed the missing tags, so links in the documentation should be valid now. In order to avoid this situation in the future, I suggest pushing the tags and releases to GH automatically with Travis CI: https://github.com/zalando-incubator/Transformer/pull/54
