### ISSUE TITLE
Har files containing PATCH http requests make transformer crash

### ISSUE THREAD

**Issue by jredrejo** [zalando-incubator/Transformer#52]
**Describe the bug**
har files containing patch requests fail

**Transformer version**
1.1.3

**To Reproduce**
Steps and input files to reproduce the behavior:
1. Create a har file with some web site using a REST api and update some field. REST uses patch http requests to do it. Attached [prueba3.zip](https://github.com/zalando-incubator/Transformer/files/3135015/prueba3.zip) as an example.

2. Run Transformer with the same command line explained in the examples
3. See error
```
  File ".../python3.6/site-packages/transformer/request.py", line 150, in from_har_entry
    method=HttpMethod[request["method"]],
  File "/usr/lib/python3.6/enum.py", line 329, in __getitem__
    return cls._member_map_[name]
KeyError: 'PATCH'
```

**Expected behavior**
A python available for locust should be produced

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version:18.04

**Additional context**

**Comment by tortila** [comment]
Thanks for reporting the bug and submitting the PR @jredrejo!
