### ISSUE TITLE
Invalid locustfile created when transforming a HAR without an associated weight file

### ISSUE THREAD

**Issue by bmaher** [zalando-incubator/transformer#65]
**Describe the bug**
Since the recommended way to use Transformer on the command-line is to redirect `stdout` to a file e.g. `transformer example.har > locustfile.py`, if during the execution of Transformer any log statements are printed then they will appear in the locustfile and cause a syntax error upon execution. An example of a scenario where this happens is if you transform a HAR file without providing a weight file.

**Transformer version**
1.2.6

**To Reproduce**

1. Prepare a HAR file but no `.weight` file
2. Run Transformer with the arguments `some_file.har > locustfile.py`
3. Open the `locustfile.py`
4. Notice how the first line will be an `[INFO]` log statement from Transformer warning about a missing a `.weight` file

**Expected behaviour**
I should be able to produce a valid locustfile without having to specify a weight file.

Honestly it's a little tricky to know what the best behaviour here should be since the INFO warning was valid and I, the user, explicitly redirected the stdout to the file.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 10.14.6

**Comment by thilp** [comment]
You're totally right, I even thought we already fixed this problem! I think the expected behaviour is to log to stderr.

**Comment by thilp** [comment]
I've added a test and locally (on Linux) I see it already pass, meaning that on my machine the logs are already sent on a different stream (stderr) than the generated code (stdout). Transformer doesn't explicitly asks for this but relies on the default configuration of the `logging` package:

https://github.com/zalando-incubator/transformer/blob/8201f0dc7abad03edfe03e7a331d1992abe6a90d/transformer/cli.py#L79-L81

Maybe the default on MacOS is different? To run the same test, @bmaher could you please try running `make test` in the `fix-log-destination` branch? That test is also passing in Travis, so it would be helpful to know if it's passing on your machine as well (meaning it is a bad test) or not (pointing towards the "different MacOS default" hypothesis).

**Comment by tortila** [comment]
I'm also on MacOS 10.14.6 and can confirm that the test passes. When I manually run `transformer examples/www.google.com.har > somefile.py` the INFO log is on the console but not in `somefile.py`. On the other hand when I run `poetry run transformer examples/www.google.com.har > somefile.py` the INFO log ends up in the file. So it looks like it's poetry that redirects stderr to stdout. @bmaher can you confirm which way did you run Transformer when you saw this issue?

**Comment by bmaher** [comment]
I can confirm @tortila's observation that it's due to running using poetry.

```
❯ transformer ~/Desktop/www.thoughtworks.com.har > locustfile.py
2019-11-14 13:48:38,948	INFO	No /Users/bmaher/Desktop/www.thoughtworks.com.weight provided for /Users/bmaher/Desktop/www.thoughtworks.com.har: assigning default weight 1 ([Errno 2] No such file or directory: '/Users/bmaher/Desktop/www.thoughtworks.com.weight')

~/personal_workspace/transformer fix-log-destination*
❯ poetry run transformer ~/Desktop/www.thoughtworks.com.har > locustfile.py
```

So my mistake in asserting that it happens when following the documented way of use, instead it happens if you're developing Transformer 😄 

Therefore I would consider this a low severity issue that could even be closed for now.

**Comment by thilp** [comment]
An immediate fix in this case could be to call `poetry shell` before, so that you don't have to use `poetry run`. Given that, with `poetry run`, Poetry wraps transformer, I think there is nothing more transformer can do unfortunately.

Feel free to reopen if you think of a better way!
